-- MySQL Script generated by MySQL Workbench
-- Mon Nov  5 18:20:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo` ENUM('ADM', 'INV', 'GES') NOT NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_investidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_investidor` (
  `id_investidor` INT NOT NULL AUTO_INCREMENT,
  `id_pessoa` INT NOT NULL,
  `saldo` DECIMAL(9,4) NULL,
  PRIMARY KEY (`id_investidor`),
  INDEX `fk_tb_investidor_tb_pessoa1_idx` (`id_pessoa` ASC),
  CONSTRAINT `fk_tb_investidor_tb_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `id_pessoa` INT NOT NULL,
  INDEX `fk_tb_administrador_tb_pessoa1_idx` (`id_pessoa` ASC),
  PRIMARY KEY (`id_administrador`),
  CONSTRAINT `fk_tb_administrador_tb_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_config_taxa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_config_taxa` (
  `id_config_taxa` INT NOT NULL AUTO_INCREMENT,
  `id_administrador` INT NOT NULL,
  `taxa_saque` DOUBLE(3,3) NULL,
  `taxa_fundo` DOUBLE(3,3) NULL,
  `data` DATE NULL,
  PRIMARY KEY (`id_config_taxa`),
  INDEX `fk_tb_config_taxa_tb_administrador1_idx` (`id_administrador` ASC),
  CONSTRAINT `fk_tb_config_taxa_tb_administrador1`
    FOREIGN KEY (`id_administrador`)
    REFERENCES `mydb`.`tb_administrador` (`id_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_transacao` (
  `id_transacao` INT NOT NULL AUTO_INCREMENT,
  `id_investidor` INT UNSIGNED NOT NULL,
  `id_config_taxa` INT NOT NULL,
  `tipo` ENUM('+', '-') NOT NULL,
  `data` DATE NOT NULL,
  `valor` DECIMAL(9,4) NOT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NOT NULL,
  PRIMARY KEY (`id_transacao`),
  INDEX `fk_tb_operacao_tb_investidor1_idx` (`id_investidor` ASC),
  INDEX `fk_tb_transacao_tb_config_taxa1_idx` (`id_config_taxa` ASC),
  CONSTRAINT `fk_tb_operacao_tb_investidor1`
    FOREIGN KEY (`id_investidor`)
    REFERENCES `mydb`.`tb_investidor` (`id_investidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_transacao_tb_config_taxa1`
    FOREIGN KEY (`id_config_taxa`)
    REFERENCES `mydb`.`tb_config_taxa` (`id_config_taxa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_gestor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_gestor` (
  `id_gestor` VARCHAR(45) NOT NULL,
  `id_pessoa` INT NOT NULL,
  `meta` DECIMAL(9,4) NULL,
  `giro_maximo` DECIMAL(9,4) NULL,
  PRIMARY KEY (`id_gestor`),
  INDEX `fk_tb_gestor_tb_pessoa1_idx` (`id_pessoa` ASC),
  CONSTRAINT `fk_tb_gestor_tb_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_aplicacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_aplicacoes` (
  `id_aplicacoes` INT NOT NULL AUTO_INCREMENT,
  `id_gestor` VARCHAR(45) NOT NULL,
  `data_compra` DATE NULL,
  `data_venda` DATE NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY (`id_aplicacoes`),
  INDEX `fk_tb_aplicacoes_tb_gestor1_idx` (`id_gestor` ASC),
  CONSTRAINT `fk_tb_aplicacoes_tb_gestor1`
    FOREIGN KEY (`id_gestor`)
    REFERENCES `mydb`.`tb_gestor` (`id_gestor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_acao` (
  `id_acao` INT NOT NULL,
  `id_aplicacoes` INT NOT NULL,
  `valor` DECIMAL(9,4) NULL,
  `descricao` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `rendimento` DECIMAL(9,4) NULL,
  `status` ENUM('ATIVO', 'VENDIDA') NULL,
  `valor_compra` VARCHAR(45) NULL,
  PRIMARY KEY (`id_acao`),
  INDEX `fk_tb_acao_tb_aplicacoes1_idx` (`id_aplicacoes` ASC),
  CONSTRAINT `fk_tb_acao_tb_aplicacoes1`
    FOREIGN KEY (`id_aplicacoes`)
    REFERENCES `mydb`.`tb_aplicacoes` (`id_aplicacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_historico_acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_historico_acao` (
  `id_historico_acao` INT NOT NULL AUTO_INCREMENT,
  `id_acao` INT NOT NULL,
  `data` DATE NULL,
  `valor` DECIMAL(9,4) NULL,
  PRIMARY KEY (`id_historico_acao`),
  INDEX `fk_tb_historico_acao_tb_acao1_idx` (`id_acao` ASC),
  CONSTRAINT `fk_tb_historico_acao_tb_acao1`
    FOREIGN KEY (`id_acao`)
    REFERENCES `mydb`.`tb_acao` (`id_acao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_solicitacao_saque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_solicitacao_saque` (
  `id_solicitacao_saque` INT NOT NULL AUTO_INCREMENT,
  `id_investidor` INT NOT NULL,
  `valor` DECIMAL(10,2) NULL,
  `data` DATE NULL,
  `status` ENUM('AGUARDANDO', 'APROVADO') NULL,
  PRIMARY KEY (`id_solicitacao_saque`),
  INDEX `fk_tb_solicitacao_saque_tb_investidor1_idx` (`id_investidor` ASC),
  CONSTRAINT `fk_tb_solicitacao_saque_tb_investidor1`
    FOREIGN KEY (`id_investidor`)
    REFERENCES `mydb`.`tb_investidor` (`id_investidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_data_saque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_data_saque` (
  `id_data_saque` INT NOT NULL AUTO_INCREMENT,
  `id_transacao` INT NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`id_data_saque`),
  INDEX `fk_tb_data_saque_tb_transacao1_idx` (`id_transacao` ASC),
  CONSTRAINT `fk_tb_data_saque_tb_transacao1`
    FOREIGN KEY (`id_transacao`)
    REFERENCES `mydb`.`tb_transacao` (`id_transacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`atualiza_saldos` AFTER INSERT ON `tb_operacao` FOR EACH ROW
BEGIN
	-- atualizar saldo do investidor
    -- e do fundo de investimentos
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
